### ISSUE TITLE
Wrong subtitles

### ISSUE THREAD

**Issue by raphaelfabeni** [wesbos/Wes-Bos-Captions#23]
Actually the subtitles are changed.
The _Speech recognition_ video has the _Geolocation_ subtitle and the _Geolocation_ video has the _Speech recognition_ subtitle.

I don't know if there is something related, but in the website, the video numbers are:

* **20** => Native speech recognition
* **21** => Geolocation based Speedometer and Compass

And in the repo it's missing the **19** and we have **21** repeated.

<img width="438" alt="screen shot 2017-01-14 at 11 17 25 am" src="https://cloud.githubusercontent.com/assets/1345662/21955115/329958be-da4b-11e6-8012-a03ff17f04ba.png">

**Comment by wesbos** [comment]
Thank you so much - will take a look into this. I must have the data wrong in my list of videos
