### ISSUE TITLE
JavaScript Drum Kit - WAV files not working in Firefox

### ISSUE THREAD

**Issue by Dudecor3** [wesbos/Wes-Bos-Captions#24]
Audio files from JavaScript Drum Kit do not work in Firefox apart from kick.wav: 

Media resource file:///C:/Users/developer/PhpstormProjects/untitled/sounds/clap.wav could not be decoded. index.html
Media resource file:///C:/Users/developer/PhpstormProjects/untitled/sounds/hihat.wav could not be decoded. index.html
Media resource file:///C:/Users/developer/PhpstormProjects/untitled/sounds/openhat.wav could not be decoded. index.html
Media resource file:///C:/Users/developer/PhpstormProjects/untitled/sounds/boom.wav could not be decoded. index.html
Media resource file:///C:/Users/developer/PhpstormProjects/untitled/sounds/ride.wav could not be decoded. index.html
Media resource file:///C:/Users/developer/PhpstormProjects/untitled/sounds/snare.wav could not be decoded. index.html
Media resource file:///C:/Users/developer/PhpstormProjects/untitled/sounds/tom.wav could not be decoded. index.html
Media resource file:///C:/Users/developer/PhpstormProjects/untitled/sounds/tink.wav could not be decoded.

**Comment by wesbos** [comment]
This is the captions repo so I'm going to close this. But your problem is that you didn't download the wav files propertly - try re-download them from github and make sure they play outside of the browser first.

**Comment by josegomes123** [comment]
I came across this problem too, just posting here for any people requiring further assistance. **If you are using Visual Studio Code Firefox preview**, the audio files will not work, it will give you the error you posted above.

 **If you try to open the same file on a normal firefox window it should work properly** (at least it did for me). I'm not sure what's the problem but that's what happened to me.
