### ISSUE TITLE
2 minute gap in episode 10 of 'Learn Node'

### ISSUE THREAD

**Issue by grawlinson** [wesbos/Wes-Bos-Captions#27]
There seems to be a 2 minute gap in episode 10, here's a snippet from the subtitle file showing the gap

```
00:01:41.780 --> 00:01:44.034 line:100% position:50% align:middle
and we'll have our block content.

00:03:54.400 --> 00:03:58.530 line:100% position:50% align:middle
Some HTML that needs to be displayed onto
the page. So that's what we're going to
```

Should prove to be a good first issue for any contributors looking to help out.

**Comment by wesbos** [comment]
Ahh - the video I submitted to the captioners initially had a block.

If anyone wants to do it, I'll send you some stickers. Otherwise I'll ship this back off to the captioners
