### ISSUE TITLE
Captions for episodes (67,68,69,70,71,72,73,74,75,76,77)

### ISSUE THREAD

**Issue by vs0uz4** [wesbos/Wes-Bos-Captions#33]
Hello @wesbos ,

His courses are fantastic, and the didactics wonderful, congratulations for the excellent work.

The course `ES6 for Everyone` received some updates, specifically two new blocks:
- Async + Await Flow Control
- ES7, ES8 + Beyond

But the repository of captions related to video lessons has not been updated, there are only `captions` to the `Map and Weak Map` video block.

Did the new added blocks get captions too? Do the captions for the episodes `(67,68,69,70,71,72,73,74,75,76,77)` have any predictions of when the captions will be sent to the repository?

**Comment by wesbos** [comment]
I've just placed an order for these caption - apologies for not having them earlier. I now have a much faster caption process where I can get the captions up before a single video is posted.

**Comment by wesbos** [comment]
these are now up!
