### ISSUE TITLE
No captions in Learn Node 

### ISSUE THREAD

**Issue by baumannzone** [wesbos/Wes-Bos-Captions#42]
Hello, I'm watching your videos through your platform (courses.wesbos.com) and at the moment, the first 3 videos of learn node, have no subtitles.  
Any idea whats happening @wesbos ? Clicking in the `[cc]` icon does nothing. 
  
Thanks.

**Comment by baumannzone** [comment]
Edit
---
Testing with Chrome (v62) in macOS high sierra (v10.13)
Second day in the videos, watching without subtitles. 
Any help?

**Edit while editing:**
It's working with Safari.

**Comment by wesbos** [comment]
Hey! Can you show me exactly which version of Chrome you are on? I'm seeing the issue on Chrome 64, but but not Chrome 62.

**Comment by baumannzone** [comment]
Sure: 
![image](https://user-images.githubusercontent.com/5422102/33577542-a4a7c4e8-d943-11e7-821b-516d027fd322.png)

Atm, I'm using firefox developer edition instead safari and works nice too

**Comment by wesbos** [comment]
Not sure what the problem was here but I've moved to a new player which has even better caption support

**Comment by CesarDenis** [comment]
@wesbos in my case on ES6 for Everyone only have EN caption.

**Comment by wesbos** [comment]
There currently are only EN captions for my videos

**Comment by CesarDenis** [comment]
I understood as I saw other translations in your repository, I thought it was published. 😄
