### ISSUE TITLE
Filenames non-MS friendly :(

### ISSUE THREAD

**Issue by jcarlosteso** [wesbos/Wes-Bos-Captions#5]
Tried to clone the repo at home (Windows 10, sorry 😳) to start my es-ES translations, but couldn't create these four files because they include a `?` in their filename:
- `ES/05 - Is Var Dead? What should I user?.txt`
- `ES/05 - Is Var Dead? What should I user?.vtt`
- `ES/58 - What are Proxies?.txt`
- `ES/58 - What are Proxies?.vtt`

**Comment by nicekiwi** [comment]
+1

**Comment by nicekiwi** [comment]
This prevents me form cloning the repo.

**Comment by adaptedbee** [comment]
+1, same problem on Windows 8

**Comment by zkriszti** [comment]
+1, cannot clone repo (Windows10). Error message says: "error: unable to create file ES6/05 - Is var Dead? What should I use?.txt: Invalid argument
error: unable to create file ES6/58 - What are Proxies?.txt: Invalid argument
error: unable to create file ES6/58 - What are Proxies?.vtt: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed."
